apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway-ingress
  namespace: katyavarlamova
spec:
  ingressClassName: nginx
  rules:
    - host: katyavarlamova.ds.com
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: gateway-service
                port:
                  number: 8080
    - host: katyavarlamova.idp.ds.com
      http:
        paths:
          - path: /api/v1/
            pathType: Prefix
            backend:
              service:
                name: provider-service
                port:
                  number: 8090
